project:
  type: website
  output-dir: .

website:
  title: "ACE"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - index.qmd
      - section: "Commands"
        contents:
          - generate.qmd
          - deconvolve.qmd
          - verify.qmd
      - section: "API"
        contents:
          - python_api.qmd
      - section: "Notes"
        contents:
          - developer_notes.qmd

format:
  html:
    theme: materia
    css: style.css