---
title: "Getting Started"
---

# ACE Configurator for ELISpot

**Source code**: [link](https://github.com/pirl-unc/ace)

**License**: Apache 2.0 License

**Latest Stable Version**: `0.1.2.0`

**Updated date**: May 6, 2025

`ACE` is a python library and command-line software for:

1. Generation of ELISpot assignments.
2. Deconvolution of hit peptides from ELISpot results.

## 01. Installation

Please first download the latest stable release of `ACE` from [here](https://github.com/pirl-unc/ace/releases)

```bash
pip install ace-<version>.tar.gz
```

## 02. Dependencies

- python==3.10.13
- pip==25.0
- numpy==1.26.4
- pandas==2.2.3
- scipy==1.15.2
- scikit-learn==1.6.1
- openpyxl=3.1.5
- setuptools==72.1.0
- pyinstaller==6.13.0
- transformers=4.30.2
- pillow==11.1.0
- eel==0.18.1
- golfy==2.5.0
- levenshtein==0.27.1
- networkx==3.4.2
- ortools==9.8.3296
- torch==2.2.2

## **Command Line Interface**

```bash
usage: ace [-h] [--version] {generate,deconvolve,verify} ...

ACE Configurator for ELISpot.

positional arguments:
  {generate,deconvolve,verify}
                        ACE sub-commands.
    generate            Generates an ELISpot experiment configuration.
    deconvolve          Deconvolve hit peptide IDs given read-outs from an ELISpot experiment.
    verify              Verifies whether an ELISpot assignment satisfies all ACE constraints.

options:
  -h, --help            show this help message and exit
  -v, --version         show program version number and exit
```

**ACE includes the following commands:** 

* [generate](generate.qmd) (generate an ELISpot configuration)
* [deconvolve](deconvolve.qmd) (deconvolve hit peptides from ELISpot results)
* [verify](verify.qmd) (verify if an ELISpot configuration is optimal)

## **Citation**

If you use `ACE` in a publication, please cite our
[publication](https://academic.oup.com/bib/article/25/1/bbad495/7510987) describing `ACE`.

