name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        activate-environment: test-env
        python-version: "3.10"

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        # Remove tmp files
        sudo rm -rf /tmp/*

        # Install conda packages
        conda env list
        conda info
        conda config --add channels defaults
        conda config --add channels bioconda
        conda config --add channels conda-forge
        conda config --set channel_priority strict
        conda install -c anaconda numpy==1.26.4
        conda install -c anaconda pandas==2.2.3
        conda install -c anaconda scipy==1.15.2
        conda install -c anaconda scikit-learn==1.6.1
        conda install -c anaconda openpyxl==3.1.5
        conda install -c anaconda networkx==3.4.2
        conda install -c anaconda pillow==11.1.0
        conda install -c conda-forge pyinstaller==6.13.0
        pip install transformers==4.30.2        
        pip install eel==0.18.1
        pip install golfy==2.5.0
        pip install levenshtein==0.27.1
        pip install ortools==9.8.3296
        pip install torch==2.2.2
        conda install pylint
        conda install coveralls
        conda install pytest
        conda install pytest-cov
  
        # Install ace
        pip install . --verbose

    - name: Run linter
      shell: bash -l {0}
      run: |
        chmod +x lint.sh
        bash lint.sh

    - name: Run unit tests
      shell: bash -l {0}
      run: |
        chmod +x unittest.sh
        bash unittest.sh